spring:
  application:
    name: openai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  chat:
    memory:
      repository:
       jdbc:
        initailize-schema: true
        schema: classpath:/schema/schema-h2db.sql
  datasource:
    url: jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: pcgs
    password: 12345

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.ai.chat.client.advisor: DEBUG




